[pytest]
pythonpath = src
filterwarnings =
    ignore:Please use `import python_multipart` instead.:PendingDeprecationWarning
    ignore:.*crypt.*deprecated.*:DeprecationWarning
    ignore:.*PydanticDeprecatedSince20.*:DeprecationWarning
    ignore:Valid config keys have changed in V2:UserWarning
