apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: codemaster-algo-compiler
  namespace: codemaster
  labels:
    app.kubernetes.io/name: codemaster
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
