apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piston-data
  namespace: codemaster
  labels:
    app.kubernetes.io/name: codemaster
    app.kubernetes.io/component: piston
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
